/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as KategoriRouteImport } from './routes/kategori'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIdRouteImport } from './routes/produk.$id'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriRoute = KategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIdRoute = ProdukIdRouteImport.update({
  id: '/produk/$id',
  path: '/produk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/profil': typeof ProfilRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/profil': typeof ProfilRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/profil': typeof ProfilRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kategori' | '/keranjang' | '/profil' | '/produk/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kategori' | '/keranjang' | '/profil' | '/produk/$id'
  id: '__root__' | '/' | '/kategori' | '/keranjang' | '/profil' | '/produk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KategoriRoute: typeof KategoriRoute
  KeranjangRoute: typeof KeranjangRoute
  ProfilRoute: typeof ProfilRoute
  ProdukIdRoute: typeof ProdukIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori': {
      id: '/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof KategoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$id': {
      id: '/produk/$id'
      path: '/produk/$id'
      fullPath: '/produk/$id'
      preLoaderRoute: typeof ProdukIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KategoriRoute: KategoriRoute,
  KeranjangRoute: KeranjangRoute,
  ProfilRoute: ProfilRoute,
  ProdukIdRoute: ProdukIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
